name: Default

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run npm ci
      run: npm ci
    - name: Run typescript checking
      run: npm run ts
    - name: Run linter checking
      run: npm run lint
    - name: Run build project
      run: npm run build --if-present
    - name: Run tests for project
      run: npm test
